// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `play.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package play4service;

public interface Play extends Ice.Object,
                              _PlayOperations, _PlayOperationsNC
{
    public static final String ice_staticId = "::play4service::Play";

    public static final long serialVersionUID = -4264946131758376044L;
}
