// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `play.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package play4service;

public interface PlayPrx extends Ice.ObjectPrx
{
    public void playGame();

    public void playGame(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_playGame();

    public Ice.AsyncResult begin_playGame(java.util.Map<String, String> __ctx);

    public Ice.AsyncResult begin_playGame(Ice.Callback __cb);

    public Ice.AsyncResult begin_playGame(java.util.Map<String, String> __ctx, Ice.Callback __cb);

    public Ice.AsyncResult begin_playGame(Callback_Play_playGame __cb);

    public Ice.AsyncResult begin_playGame(java.util.Map<String, String> __ctx, Callback_Play_playGame __cb);

    public Ice.AsyncResult begin_playGame(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_playGame(IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public Ice.AsyncResult begin_playGame(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb);

    public Ice.AsyncResult begin_playGame(java.util.Map<String, String> __ctx, 
                                          IceInternal.Functional_VoidCallback __responseCb, 
                                          IceInternal.Functional_GenericCallback1<Ice.Exception> __exceptionCb, 
                                          IceInternal.Functional_BoolCallback __sentCb);

    public void end_playGame(Ice.AsyncResult __result);
}
