// **********************************************************************
//
// Copyright (c) 2003-2016 ZeroC, Inc. All rights reserved.
//
// This copy of Ice is licensed to you under the terms described in the
// ICE_LICENSE file included in this distribution.
//
// **********************************************************************
//
// Ice version 3.6.2
//
// <auto-generated>
//
// Generated from file `hello.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package hello4service;

public interface Hello extends Ice.Object,
                               _HelloOperations, _HelloOperationsNC
{
    public static final String ice_staticId = "::hello4service::Hello";

    public static final long serialVersionUID = -4821883036317132044L;
}
